//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartReporter.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ADMINISTRATOR               101
#define IDS_USER                        102
#define IDS_LINELIST_TO_ORA_SETTING_TITLE 103
#define IDS_RIBBON_FILE                 104
#define IDS_RIBBON_EXIT                 105
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_LineControlManaTYPE         130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_EDIT_MENU                   306
#define IDD_LOGIN                       310
#define IDD_REGISTER_MACHINE            312
#define IDD_LINE_LIST_TO_ORA            313
#define IDD_DIALOG1                     314
#define IDD_LINELISTTOORA_FORM          314
#define IDD_LINE_LIST_CONVERT_CTRL      317
#define IDD_WORK_STATUS                 318
#define IDI_SHEET                       319
#define IDI_SELECT_ALL                  320
#define IDI_UNSELECT_ALL                321
#define IDC_APP_HAND                    323
#define IDD_CUSTOM_DATA_REPORT          324
#define IDD_ORA_DATA_REPORT             325
#define IDB_LLTOORA_APP                 326
#define IDB_TREE_IMG                    327
#define IDB_STATE                       328
#define IDI_REFRESH                     329
#define IDB_BITMAP_LIST_HEAD            330
#define IDI_ICON1                       332
#define IDI_CHECK                       332
#define IDD_DIALOG_PROPERTY             333
#define IDD_CUSTOM_REPORT_PROPERTY      334
#define IDB_LOGO                        336
#define IDB_MAIN                        337
#define IDB_BUTTONS                     338
#define IDB_FILESMALL                   339
#define IDB_FILELARGE                   340
#define IDC_EDIT_ORA_PASSWORD           1000
#define IDC_STATIC_ABOUT                1000
#define IDC_EDIT_NAME                   1001
#define IDC_STATIC_LOGO                 1001
#define IDC_COMBO1                      1002
#define IDC_COMBO_HEAD_LABEL            1002
#define IDC_BUTTON_SELECT_ALL           1013
#define IDC_BUTTON_UNSELECT_ALL         1014
#define IDC_EDIT_DESIGN_DLL_FILE_PATH   1042
#define IDC_BUTTON_DESIGN_DDL           1043
#define IDC_EDIT_STD_NOTE_FILE_PATH     1045
#define IDC_COMBO_USER                  1046
#define IDC_BUTTON_STD_NOTE             1046
#define IDC_EDIT_PASSWORD               1047
#define IDC_EDIT_PDS_PRO_NAME           1051
#define IDC_COMBO_PROJECT_NAME          1060
#define IDC_LIST_KEY                    1062
#define IDC_BUTTON_LINE_LIST_CONVERT    1062
#define IDC_EDIT_RowNum                 1063
#define IDC_COMBO_CONV_RESULT_COL       1064
#define IDC_LIST_LINE_LIST              1065
#define IDC_LIST_SHEET_NAME             1066
#define IDC_BUTTON_LOAD_SHEET_NAME      1067
#define IDC_BUTTON_EXCEL_EXPORT         1069
#define IDC_STATIC_AREA_NO              1070
#define IDC_BUTTON_SelectExcel          1071
#define IDC_STATIC_ShowExcelName        1072
#define IDC_SELECT_ALL_AREA             1074
#define IDC_TREE_AREA                   1080
#define IDC_BUTTON_REFRESH              1082
#define IDC_STATIC_LABEL                1083
#define IDC_RADIO_INCH                  1085
#define IDC_BUTTON_QUERY                1086
#define IDC_RADIO_METRIC                1086
#define IDC_COMBO_UNIT                  1087
#define IDC_EDIT_HEAD_LABEL             1088
#define IDC_EDIT_SQL_FILE               1089
#define IDC_BUTTON_SQL_FILE             1090
#define IDC_EDIT_EXCEL_FILE             1091
#define IDC_BUTTON_EXCEL_FILE           1092
#define IDC_EDIT_START_ROW              1093
#define IDC_BUTTON_ADD                  1094
#define IDC_EDIT_MACHINE_KEY            1095
#define IDC_EDIT_DISCIPLINE             1095
#define IDC_BUTTON_SEND_MAIL            1096
#define IDC_BUTTON_DELETE               1096
#define IDC_STATIC_1                    1102
#define IDC_PROGRESS                    1119
#define IDC_STATIC_2                    1122
#define IDC_STATIC_3                    1123
#define IDC_STATIC_CONVERT              1124
#define IDC_STATIC_ROW_NUMBER           1125
#define IDC_STATIC_CONV_RESULT_COL      1126
#define IDC_EDIT_SERVICE_NAME           1156
#define IDC_EDIT_USER_NAME              1157
#define IDC_BUTTON_CONNECT_TEST         1158
#define ID_VIEW_ORACLE_SETTING          32771
#define ID_VIEW_LINE_CONVERT            32772
#define ID_VIEW_ORA_DATA_REPORT         32773
#define ID_FILE_SETTING                 32774
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        341
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
