//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Admin.rc
//
#define ID_INDICATOR_UPDATE             1
#define IDD_ABOUTBOX                    100
#define IDD_ADMIN_FORM                  101
#define IDR_MAINFRAME                   128
#define IDR_ADMINTYPE                   129
#define IDS_RIBBON_FILE                 129
#define IDD_DIALOG_PROJECT_DEF          130
#define IDS_RIBBON_EXIT                 130
#define IDD_DIALOG_USER                 131
#define ID_TOOLS_GENERAL_SETTING        131
#define IDD_DIALOG_PROJECT_ACCESS       132
#define IDS_USER_APP_SETTING_TITLE      132
#define IDS_ADMIN_SETTING_TITLE         132
#define IDD_DIALOG_PROJECT_SETTING      133
#define IDI_RIGHT_ARROW                 134
#define IDI_DEL                         135
#define IDI_SAVE                        136
#define IDI_NEW                         137
#define IDB_ADD                         142
#define IDB_REMOVE                      144
#define IDI_REFRESH                     145
#define IDD_PROJECT_SETTING_DEMO        149
#define IDD_BORDER_SETTING              157
#define IDC_CURSOR_PEN                  161
#define IDC_CURSOR_CROSS                162
#define IDI_OK                          163
#define IDD_SETTING                     163
#define IDD_LINE_DATA_SETTING           164
#define IDD_ISO_EDIT_SETTING            165
#define IDB_LEDS                        165
#define IDD_FILE_NAME_FORMAT            166
#define IDI_ADD                         167
#define IDI_SETTING                     169
#define IDC_HAND_CUR                    170
#define IDI_REMOVE                      172
#define IDC_CURSOR_SELECT               174
#define IDD_WORK_STATUS                 174
#define IDD_DRAWING_REPORT              175
#define IDI_SELECT_ALL                  181
#define IDD_BM_REPORT_SETTING           181
#define IDI_UNSELECT_ALL                182
#define IDD_ORACLE_SETTING              184
#define IDI_ORACLE                      185
#define IDI_REFRESH2                    191
#define IDD_REF_DATA_SETTING            192
#define IDD_REVISION_STAGE              193
#define IDC_HAND_CUR_CUR                194
#define IDB_BITMAP1                     195
#define IDB_HICOLOR_TOOLBAR             195
#define IDB_HICOLOR_TOOLBAR32           195
#define IDB_SETTING                     196
#define IDI_BM_REPORT                   196
#define IDD_ISO_FILE_SETTING            196
#define IDB_BITMAP2                     197
#define IDB_ADMIN_TREE                  197
#define IDB_BITMAP3                     198
#define IDB_LOGO                        198
#define IDD_SMART_ISO_DIFF_SETTING      200
#define IDD_GENERAL_SETTING             201
#define IDB_CLOUD_MARK                  202
#define IDB_BUTTONS                     203
#define IDB_MAIN                        204
#define IDB_FILELARGE                   205
#define IDB_FILESMALL                   206
#define IDI_ICON1                       208
#define IDI_LENGTH                      208
#define IDI_ICON2                       209
#define IDI_SITE                        209
#define IDB_CHECKBOXES                  210
#define IDI_ISO_EDIT_SETTING            212
#define IDC_EDIT_PASSWORD               1000
#define IDC_LIST_USER                   1001
#define IDC_LIST_ASSIGNED_USER          1001
#define IDC_EDIT_DESIGN_PASSWORD        1001
#define IDC_STATIC_USER_LIST            1002
#define IDC_COMBO_USER                  1003
#define IDC_BUTTON_ASSIGN               1004
#define IDC_STATIC_USER                 1005
#define IDC_BUTTON1                     1006
#define IDC_BUTTON_NEXT                 1006
#define IDC_BUTTON_ADD_USER             1006
#define IDC_BUTTON_REFRESH              1006
#define IDC_BUTTON_BORDER_FILE          1006
#define IDC_BUTTON_NEW                  1006
#define IDC_BUTTON_DRAWINGREPORTOPEN    1006
#define IDC_BUTTON_DESIGN_DDL           1006
#define IDC_BUTTON_ADD1                 1006
#define IDC_BUTTON_REV_ISO_FOLDER       1006
#define IDC_BUTTON_DELETE_MAPPING       1006
#define IDC_LIST_PROJECT_ACCESS         1007
#define IDC_STATIC_ASSIGN_USER          1007
#define IDC_BUTTON_DEL1                 1007
#define IDC_BUTTON2                     1007
#define IDC_BUTTON_NEW_MAPPING          1007
#define IDC_BUTTON_REMOVE               1008
#define IDC_BUTTON_ADD2                 1008
#define IDC_BUTTON_PREV                 1009
#define IDC_BUTTON_DEL2                 1009
#define IDC_BUTTON_DEL                  1010
#define IDC_BUTTON_ADD3                 1010
#define IDC_BUTTON_SAVE                 1011
#define IDC_BUTTON_DEL3                 1011
#define IDC_EDIT_FIELD_NAME             1012
#define IDC_BUTTON_ADD4                 1012
#define IDC_BUTTON_DEL4                 1013
#define IDC_BUTTON_NEW_COL              1014
#define IDC_BUTTON_ADD5                 1014
#define IDC_COMBO_FIELD_TYPE            1015
#define IDC_BUTTON_DEL5                 1015
#define IDC_EDIT_PDS_PRJ_NAME           1015
#define IDC_BUTTON_REMOVE_USER          1016
#define IDC_BUTTON_GRADE_ADD            1016
#define IDC_BUTTON_CONNECTION_TEST      1016
#define IDC_BUTTON_GRADE_DEL            1017
#define IDC_BUTTON_CONNECTION_TEST2     1017
#define IDC_BUTTON_DESIGN_CONNECTION_TEST 1017
#define IDC_LIST_PROJECT_USER           1018
#define IDC_EDIT_HOST                   1018
#define IDC_BUTTON_RsDel                1025
#define IDC_BUTTON_RvDel                1026
#define IDC_EDIT_BORDER_FILE_PATH       1027
#define IDC_EDIT_BORDER_FILE_PATH2      1028
#define IDC_EDIT_IGNORE_CHAR            1028
#define IDC_BUTTON_RES_CREATE           1030
#define IDC_BUTTON_REV_CREATE           1031
#define IDC_STATIC_RES                  1032
#define IDC_STATIC_REV                  1033
#define IDC_STATIC_LINE_DATA            1034
#define IDC_EDIT_ISO_DWG_FOLDER         1035
#define IDC_LIST_LINE_DATA_FIELD        1037
#define IDC_STATIC_2                    1037
#define IDC_STATIC_GROUP_BOX1           1038
#define IDC_EDIT_OUTPUT_ISO_DWG_FOLDER  1039
#define IDC_STATIC_PRODUCT_BOM_FOLDER   1040
#define IDC_LIST_FILE_NAME_ITEM         1041
#define IDC_EDIT_PRODUCT_BOM_FOLDER     1041
#define IDC_LISTBUDDY                   1042
#define IDC_STATIC_DATABASE_REFERENCE_KEY 1042
#define IDC_EDIT_DELIMITER              1043
#define IDC_BUTTON_ADD                  1044
#define IDC_EDIT_INPUT_FILE_NAME        1045
#define IDC_BUTTON_ADD6                 1045
#define IDC_EDIT_OUTPUT_FILE_NAME       1046
#define IDC_BUTTON_INPUT_FILE_NAME      1047
#define IDC_BUTTON_OUTPUT_FILE_NAME     1048
#define IDC_STATIC_GROUP_BOX2           1049
#define IDC_BUTTON_DATABASE_REFERENCE_KEY 1049
#define IDC_STATIC_GROUP1               1050
#define IDC_STATIC_OUTPUT_GROUP_BOX     1050
#define IDC_RADIO_ALPHABETIC            1051
#define IDC_BUTTON_REFRESH_SOURCE_FOLDER 1051
#define IDC_BUTTON_OUTPUT_FILE_EXT      1051
#define IDC_EDIT_PIPE_CUT_LENGTH        1051
#define IDC_EDIT_FILE_NAME_EXT          1051
#define IDC_RADIO_NUMERIC               1052
#define IDC_BUTTON_REFRESH_OUTPUT_FOLDER 1052
#define IDC_EDIT_DATABASE_REFERENCE_KEY 1052
#define IDC_STATIC_PRIMARY_KEY          1053
#define IDC_EDIT_OUTPUT_FILE_EXT        1053
#define IDC_STATIC_ISSUE_DATE           1054
#define IDC_LIST_PRIMARK_KEY            1055
#define IDC_LIST_ISSUE_DATE             1056
#define IDC_GROUP_LINE_DATA_MODULE_KEY  1056
#define IDC_LIST_LINE_DATA_MODULE_KEY   1057
#define IDC_DATETIMEPICKER1             1060
#define IDC_EDIT_DRAWINGREPORT          1061
#define IDC_EDIT_DRAWINGREPORT2         1062
#define IDC_EDIT_DWG_REPORT_TEMPLATE    1062
#define IDC_EDIT_ExlRow                 1064
#define IDC_STATIC_ROW                  1065
#define IDC_EDIT_REVSTART               1066
#define IDC_LIST_SHEET_NAME             1066
#define IDC_EDIT_REVEND                 1067
#define IDC_BUTTON_LOAD_SHEET_NAME      1067
#define IDC_STATIC_REVISION             1068
#define IDC_COMBO_REV                   1069
#define IDC_BUTTON_SelectExcel          1071
#define IDC_STATIC_ShowExcelName        1072
#define IDC_CHECK_ETC                   1073
#define IDC_STATIC_IDMS_KEY             1076
#define IDC_EDIT_DESIGN_DDL_FILE_PATH   1080
#define IDC_STATIC_ORAKEY               1085
#define IDC_COMBO_ORAKEY                1088
#define IDC_STATIC_IDMSKEY              1089
#define IDC_EDIT_IDMSKEY                1090
#define IDC_BUTTON_IDMSKEY              1091
#define IDC_STATIC_SHOW_SET             1092
#define IDC_RADIO_ALPHPLUSNUM           1093
#define IDC_STATIC_EX                   1094
#define IDC_STATIC_EX1                  1095
#define IDC_STATIC_EX3                  1095
#define IDC_STATIC_EX2                  1096
#define IDC_STATIC_COL                  1097
#define IDC_STATIC_PROUDCT_BOM_FOLDER_EX 1097
#define IDC_EDIT_ExlColumn              1098
#define IDC_LIST_DATA_NAME              1099
#define IDC_CHECK_REV_DATA              1100
#define IDC_STATIC_ROW_COUNT_PER_SHEET  1101
#define IDC_EDIT_ID                     1102
#define IDC_EDIT_ExlColumn2             1102
#define IDC_EDIT_ROW_COUNT_PER_SHEET    1102
#define IDC_EDIT_AREA                   1103
#define IDC_STATIC_ID                   1104
#define IDC_STATIC_AREA                 1105
#define IDC_LIST_MAPPING                1107
#define IDC_STATIC_MAPPING              1108
#define IDC_STATIC_LOADING_RULE         1108
#define IDC_BUTTON_ADD_ALPHA_PLUS_NUM   1109
#define IDC_STATIC_MAPPING2             1109
#define IDC_GROUP_MAPPING_FOR_INSERT    1109
#define IDC_LIST_ALPHA_PLUS_NUM         1110
#define IDC_EDIT_MSTATION_PATH          1110
#define IDC_BUTTON_DELETE_ALPHA_PLUS_NUM 1111
#define IDC_BUTTON_MSTATION             1111
#define IDC_EDIT_ALPHA_PLUS_NUM         1112
#define IDC_STATIC_ISO_MAN_KEY          1113
#define IDC_EDIT_SPEC_FILE_FOLDER       1114
#define IDC_STATIC_LINE_DATA_MODULE_KEY 1114
#define IDC_EDIT_STANDARD_NOTE_FILE     1115
#define IDC_GROUPBOX_PRODUCT_BOM_FOLDER 1115
#define IDC_GROUPBOX_FOLDER_SETTING     1115
#define IDC_COMBO_UNIT                  1116
#define IDC_GROUPBOX_FOLDER_SETTING2    1116
#define IDC_GROUPBOX_HEADER_INFO        1116
#define IDC_COMBO_DRAWING_TYPE          1117
#define IDC_GROUPBOX_BM_FORMAT          1117
#define IDC_EDIT_WORKING_UNIT           1118
#define IDC_EDIT_DVCS_E                 1119
#define IDC_COMBO_GRADE1                1119
#define IDC_PROGRESS                    1119
#define IDC_EDIT_DVCS_EL                1120
#define IDC_EDIT_GRADE_SUFFIX1          1120
#define IDC_EDIT_DVCS_N                 1121
#define IDC_LIST_GRADE1                 1121
#define IDC_COMBO_GRADE2                1122
#define IDC_EDIT_GRADE_SUFFIX2          1123
#define IDC_STATIC_3                    1123
#define IDC_LIST_GRADE2                 1124
#define IDC_COMBO_GRADE3                1125
#define IDC_STATIC_ROW_NUMBER           1125
#define IDC_EDIT_GRADE_SUFFIX3          1126
#define IDC_LIST_GRADE3                 1127
#define IDC_COMBO_GRADE4                1128
#define IDC_EDIT_GRADE_SUFFIX4          1129
#define IDC_LIST_GRADE4                 1130
#define IDC_COMBO_GRADE5                1131
#define IDC_EDIT_GRADE_SUFFIX5          1132
#define IDC_LIST_GRADE5                 1133
#define IDC_CHECK1                      1134
#define IDC_CHECK2                      1135
#define IDC_CHECK3                      1136
#define IDC_CHECK4                      1137
#define IDC_CHECK5                      1138
#define IDC_EDIT_DRWN_BY                1140
#define IDC_EDIT_CHECKED_BY             1141
#define IDC_EDIT_APPROVED_BY            1142
#define IDC_EDIT_GRADE_PREFIX           1143
#define IDC_EDIT_GRADE_DESC             1144
#define IDC_LIST_GRADE                  1145
#define IDC_CHECK_AUTO                  1146
#define IDC_EDIT_REVIEWED_BY            1146
#define IDC_LIST_CURRENT_LINE_DATA      1147
#define IDC_RADIO1                      1148
#define IDC_RADIO_PDS_DATA_UPDATE_ON    1148
#define IDC_RADIO_COLUMN_DATA           1148
#define IDC_RADIO2                      1149
#define IDC_RADIO_ISSUE_DATE_FORMAT_NO_1 1149
#define IDC_RADIO_PDS_DATA_UPDATE_OFF   1149
#define IDC_RADIO_MATL_DESC             1149
#define IDC_RADIO_ISSUE_DATE_FORMAT_NO_2 1150
#define IDC_EDIT_ISSUE_DATE_DELIMITER   1151
#define IDC_STATIC_ISSUE_DATE_DELIMITER 1152
#define IDC_RADIO_ISSUE_DATE_FORMAT_NO_3 1153
#define IDC_STATIC_GRADE                1153
#define IDC_CHECK_MANUAL                1154
#define IDC_RADIO_ISSUE_DATE_FORMAT_NO_4 1154
#define IDC_STATIC_DOT                  1155
#define IDC_STATIC_ABOUT                1156
#define IDC_EDIT_SERVICE_NAME           1156
#define IDC_RADIO_AUTOMATIC             1157
#define IDC_EDIT_USER_NAME              1157
#define IDC_RADIO_AUTOMATIC2            1158
#define IDC_RADIO_MANUAL                1158
#define IDC_EDIT_ROW                    1158
#define IDC_EDIT_DESIGN_USER_NAME       1158
#define IDC_EDIT_COL                    1159
#define IDC_RADIO_TEXT_FILE             1160
#define IDC_RADIO_TEXT_FILE2            1161
#define IDC_RADIO_EXCEL                 1161
#define IDC_RADIO_GET_PLAN_DWG_ON       1161
#define IDC_RADIO_GET_PLAN_DWG_ON2      1162
#define IDC_RADIO_GET_PLAN_DWG_OFF      1162
#define IDC_CHECK_ONE_SHEET             1162
#define IDC_STATIC_DRAWINGREPORT        1163
#define IDC_STATIC_SETTING_BOX          1164
#define IDC_CHECK_LEVEL                 1165
#define IDC_STATIC_DWG_REPORT_TEMPLATE  1165
#define IDC_CHECK_COLOR                 1166
#define IDC_CHECK_STYLE                 1167
#define IDC_CHECK_WEIGHT                1168
#define IDC_EDIT_LEVEL                  1169
#define IDC_EDIT_PIPE_COLOR             1170
#define IDC_EDIT_COLOR                  1171
#define IDC_EDIT_PIPE_LEVEL             1171
#define IDC_EDIT_STYLE                  1172
#define IDC_EDIT_PIPE_WEIGHT            1172
#define IDC_EDIT_WEIGHT                 1173
#define IDC_EDIT_CLOUD_MARK_LEVEL       1173
#define IDC_EDIT_CLOUD_MARK_COLOR       1174
#define IDC_EDIT_CLOUD_MARK_WEIGHT      1175
#define IDC_EDIT_CLOUD_MARK_ARC_MIN     1176
#define IDC_EDIT_CLOUD_MARK_ARC_MAX     1177
#define IDC_RADIO_PDS_ISO               1178
#define IDC_RADIO_PDMS_ISO              1179
#define IDC_EDIT_CLOUD_MARK_OFFSET      1180
#define IDC_EDIT1                       1181
#define IDC_EDIT_REV_ISO_FOLDER         1181
#define IDC_EDIT_LOAD_RULE1             1181
#define IDC_EDIT_LOADING_RULE1          1181
#define IDC_EDIT_KEYWORD_FOR_BOLT_LENGTH 1181
#define IDC_CHECK_LOADING_RULE1         1182
#define IDC_CHECK_LOADING_RULE2         1183
#define IDC_STATIC_CLOUD_MARK           1183
#define IDC_STATIC_HEADER_TEXT_GRID_CTRL 1185
#define IDC_STATIC_GROUP_CHECK_BOX      1186
#define IDC_CHECK_PDS_DATA_UPDATE       1187
#define IDC_STATIC_LINE_LIST_IMPORT     1188
#define IDC_BUTTON_LINE_LIST_IMPORT     1189
#define IDC_STATIC_REV_NO_DEFINE        1190
#define IDC_STATIC_REV_USER             1191
#define IDC_STATIC_SELECT_REV_NO        1192
#define IDC_COMBO1                      1193
#define IDC_COMBO_START_ROW             1193
#define IDC_COMBO_NEXT_COLUMN           1194
#define IDB_LIST_HEADER                 20001
#define ID_APP_CLOSE                    32771
#define ID_TO_USERAPP                   32772
#define ID_TOOLS_LINELIST_DATA_IMPORT   32774
#define ID_TOOLS_LINELIST_DATA          32774
#define ID_TOOLS_SETTING                32775
#define IDS_ISO_DWG_FILE_FOLDER         61446
#define IDS_ASK_CREATE_TABLE            61447
#define IDS_ASK_DELETE_COLUMN           61448
#define IDS_WARNING_DELETE_COLUMN       61449
#define IDS_WARNING_CHANGE_COLUMN       61450
#define IDS_ERROR_WRITE_INI_FILE        61451
#define IDS_WARNING_DUPLICATED_DESC     61452
#define IDS_WARNING_DELETE_ISSUE_DATE   61453
#define IDS_WARNING_LESS_OR_EQUAL_ISSUE_DATE 61454
#define IDS_ERROR_CREATE_WND            61455
#define IDS_NEED_FIELD                  61456
#define IDS_DB_CONNECTION_FAIL          61457
#define IDS_TREE_USER                   61458
#define IDS_TREE_IDMS_DATABSE_SETTING   61459
#define IDS_TREE_SETTING                61460
#define IDS_TREE_PROJECT_ACCESS         61461
#define IDS_TREE_ADMINISTRATOR          61462
#define IDS_ASSIGN_OR_DELETE_USERS      61463
#define IDS_LINEMAN_DATA_IMPORT         61464
#define IDS_NOT_ADMITTED_CHAR           61478

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        213
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
