//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UserApp.rc
//
#define IDC_BUTTON_PROJECT_SETUP        3
#define IDC_BUTTON_EXPORT               3
#define IDC_BUTTON_RESET_ACTIVATE_CODE  4
#define IDI_DOWN                        35
#define IDI_EMPTY                       36
#define IDI_UP                          39
#define IDD_ABOUTBOX                    100
#define IDD_USERAPP_FORM                101
#define IDD_LOGIN                       102
#define IDD_ISOEDITFORMHOLDER           103
#define IDR_MAINFRAME                   128
#define IDR_USERAPTYPE                  129
#define IDS_RIBBON_FILE                 129
#define IDS_PDS                         130
#define IDD_LINE_LIST_FORM              131
#define IDS_RIBBON_EXIT                 131
#define IDD_LINE_LIST_SELECT_OPTION1    132
#define ID_FILE_SMART_REPORTER          132
#define IDI_NEW                         132
#define IDD_LINE_LIST_SELECT_OPTION2    133
#define ID_FILE_ISO_CREATOR             133
#define IDI_CALENDAR                    134
#define ID_INDICATOR_UPDATE             134
#define ID_SHOW_WORKSPACEBAR            135
#define IDI_ON_ENTER                    136
#define ID_SHOW_OUTPUTBAR               136
#define IDI_MODIFY                      137
#define IDS_ABOUTBOX                    137
#define IDB_SYSTEM                      137
#define IDI_COPY                        138
#define IDB_PROJECT                     138
#define IDS_JOB_CREATED_TIME            138
#define IDS_OK_CREATE_JOB               139
#define IDI_INSERT                      140
#define IDS_OK_UPDATE_JOB               140
#define IDB_USER_APP_TREE               141
#define IDI_CANCEL                      141
#define IDI_NOTE                        142
#define IDD_PROJECT                     142
#define IDI_BULLET                      143
#define IDI_OK                          144
#define IDB_USER_APP                    144
#define IDD_LINE_LIST_CONVERT           148
#define IDD_BACKUP_DATA                 148
#define IDD_INDEX_REPORT                150
#define IDD_ISO_EDIT                    151
#define IDD_BM_REPORT                   152
#define IDR_SCI_ACCELERATOR             153
#define IDD_DIALOG_QUALIFIED_LINE       154
#define IDD_DIALOG_VIEW_LOG_FILE        155
#define IDD_DIALOG_BM_LOG_FILE          156
#define IDD_DIALOG_PDS_LINE_DATA        158
#define IDR_LINE_DATA                   159
#define IDD_ISO_EDIT_OPTION             161
#define IDD_BM_REPORT_OPTION            162
#define IDD_LINE_CONVERT_OUTPUT_FORM    164
#define IDD_BACKUP_OUTPUT_FORM          164
#define IDR_ISO_EDIT                    165
#define IDR_ISSUE_MANAGER               165
#define IDR_DRAWING_REPORT              166
#define IDD_LINE_DATA_SETTING           167
#define IDI_SETTING                     169
#define IDD_NEW_LINE_DATA               171
#define IDD_ISSUE                       171
#define IDI_COMMIT                      173
#define IDD_WORK_STATUS                 174
#define IDR_LINE_LIST                   175
#define IDD_BACKUP_HISTORY              178
#define IDI_SHOW_LOG                    179
#define IDD_LINE_LIST_CONVERT_CTRL      179
#define IDD_LINE_DATA_EDIT              179
#define IDI_SHEET                       180
#define IDD_DRAWING_REPORT_LOG_FILE     180
#define IDI_SELECT_ALL                  181
#define IDI_UNSELECT_ALL                182
#define IDB_BITMAP_MULTI_BOXES          183
#define IDB_BITMAP_BOX                  184
#define IDI_IMPORT                      185
#define IDB_MARGIN_ICONS                187
#define IDC_MARGIN_CURSOR               188
#define IDD_ISO_EDIT_OPTION2            191
#define IDD_DIALOG_SORTSETTING          192
#define IDD_INSERT_TO_PDS               193
#define IDD_WRITE_PDS                   194
#define IDI_ORACLE                      195
#define IDI_BM_REPORT                   196
#define IDD_ISO_EDIT_SETTING            196
#define IDI_LINE_DATA_SETTING           197
#define IDD_DIALOG_GETPDS_LOG_FILE      211
#define IDI_ISO_EDIT_SETTING            212
#define IDD_DIALOG_PRINT                213
#define IDD_DRAWING_PLOTTING            216
#define IDD_GET_PDS                     218
#define IDI_SAVE                        219
#define IDI_ADD                         220
#define IDD_GETDATA_FROM_IDF            221
#define IDB_LOGO                        222
#define IDD_SELECT_ISSUE_DATA           222
#define IDI_ICON1                       223
#define IDI_SORT                        223
#define ID_SMART_ISO_DIFF               224
#define IDB_MAIN                        225
#define IDB_BUTTONS                     226
#define IDB_FILESMALL                   227
#define IDB_FILELARGE                   228
#define IDI_ROOT                        229
#define IDI_PLANT                       230
#define IDI_AREA                        231
#define IDI_UNIT                        232
#define IDI_ICON2                       233
#define IDI_SECTION                     233
#define IDI_ICON3                       234
#define IDI_RUN                         234
#define IDD_DIALOG1                     235
#define IDD_REPLACE                     236
#define IDI_ICON4                       237
#define IDI_RESET_ACTIVATE_CODE         237
#define IDB_CHECKBOXES                  238
#define IDI_ISO_DWG                     239
#define IDI_ICON5                       240
#define IDI_MSTN                        240
#define IDC_LIST_LINE_LIST              1000
#define IDC_EDIT_NAME                   1001
#define IDC_HAND_CUR                    1001
#define IDC_HAND_CUR_CUR                1001
#define IDC_COMBO_PROJECT               1004
#define IDC_COMBO_USER                  1005
#define IDC_COMBO_PLANT                 1006
#define IDC_EDIT_PASSWORD               1006
#define IDC_COMBO_AREA                  1007
#define IDC_COMBO_MODULE                1007
#define IDC_EDIT_PROJECT_NAME           1007
#define IDC_COMBO_UNIT                  1008
#define IDC_STATIC_LOGIN                1008
#define IDC_EDIT_JOB_NO                 1008
#define IDC_LIST_ISSUE_DATE             1009
#define IDC_COMBO_REVISION              1009
#define IDC_EDIT_CLIENT_NAME            1009
#define IDC_EDIT_SITE_PASSWORD          1009
#define IDC_LIST_QUALIFIED_LINE         1010
#define IDC_LIST_ISSUED_DATE            1010
#define IDC_LIST_JOB                    1010
#define IDC_EDIT_SITE_PASSWORD2         1010
#define IDC_EDIT_SITE                   1010
#define IDC_LIST_GRADE_DEFINE           1011
#define IDC_COMBO_REVISION2             1011
#define IDC_COMBO_STATUS                1011
#define IDC_BUTTON_DEL                  1011
#define IDC_BUTTON_SELECT               1012
#define IDC_LIST_REV_NO_IN_GRADE        1012
#define IDC_EDIT_PROJECT_DESC           1012
#define IDC_BUTTON_SELECT_ALL           1013
#define IDC_BUTTON_CREATE               1013
#define IDC_CHECK_ISSUE_DATE            1014
#define IDC_BUTTON_COPY                 1014
#define IDC_BUTTON_UNSELECT_ALL2        1014
#define IDC_BUTTON_UNSELECT_ALL         1014
#define IDC_BUTTON_MODIFY               1015
#define IDC_BUTTON_REVERSE              1015
#define IDC_BUTTON_DELETE_ISSUE         1015
#define IDC_BUTTON_INSERT               1016
#define IDC_BUTTON_DELETE               1017
#define IDC_EDIT_FOLDER                 1017
#define IDC_BUTTON_DELETE2              1018
#define IDC_BUTTON_SAVE_QUERY_CLAUSE    1018
#define IDC_BUTTON_QUALIFIED_LINE       1019
#define IDC_BUTTON_SORT                 1019
#define IDC_BUTTON_PRINT                1020
#define IDC_BUTTON_SORT2                1020
#define IDC_BUTTON_SET_DISPLAY_COLUMN   1020
#define IDC_EDIT_PROJECT_NO             1023
#define IDC_EDIT_PDS_NAME               1024
#define IDC_STATIC_EX                   1025
#define IDC_STATIC_REVISION_DATA        1044
#define IDC_EDIT2                       1049
#define IDC_LIST_DEFINITION_TABLE       1050
#define IDC_EDIT1                       1051
#define IDC_EDIT_FILE_NAME_EXT          1051
#define IDC_EDIT_UNIT_X                 1051
#define IDC_EDIT_ISO_FOLDER             1051
#define IDC_EDIT_FIND                   1051
#define IDC_BUTTON1                     1052
#define IDC_LISTBUDDY                   1052
#define IDC_BUTTON_COMMIT               1052
#define IDC_BUTTON_SHOW_LOG             1052
#define IDC_BUTTON_UN_SELECT_ALL        1052
#define IDC_LISTSORTBUDDY               1052
#define IDC_BUTTON_INSERT_ORA           1052
#define IDC_EDIT_DVCS_X                 1052
#define IDC_BUTTON_EXCEL_EXPORT         1052
#define IDC_EDIT_REPLACE                1052
#define IDC_BUTTON_UPDATE_ORACLE        1052
#define IDC_BUTTON2                     1053
#define IDC_BUTTON_ExcelView            1053
#define IDCANCLE                        1053
#define IDC_BUTTON_LINE_DATA_REPORT     1053
#define IDC_EDIT_UNIT_Y                 1053
#define IDC_BUTTON3                     1054
#define IDC_BUTTON_DOWN                 1054
#define IDC_EDIT_DVCS_Y                 1054
#define IDC_EDIT3                       1055
#define IDC_EDIT_UNIT_Z                 1055
#define IDC_EDIT4                       1056
#define IDC_EDIT_DVCS_Z                 1056
#define IDC_EDIT5                       1057
#define IDC_EDIT6                       1058
#define IDC_EDIT7                       1060
#define IDC_COMBO1                      1061
#define IDC_COMBO_PRINTER               1061
#define IDC_COMBO_PRINTER_LIST          1061
#define IDC_COMBO_QUERY                 1061
#define IDC_BUTTON_LINE_LIST_CONVERT    1062
#define IDC_EDIT_RowNum                 1063
#define IDC_LIST_CONVERT                1066
#define IDC_LIST_SHEET_NAME             1066
#define IDC_BUTTON_ExcelName            1067
#define IDC_BUTTON_LOAD_SHEET_NAME      1067
#define IDC_BUTTON_SelectExcel          1071
#define IDC_STATIC_ShowExcelName        1072
#define IDC_LIST_LOG                    1072
#define IDC_CHECK1                      1073
#define IDC_CHECK_WBS_EXCEPTION         1073
#define IDC_CHECK_MAKE_NTR_FILE         1074
#define IDC_TREE1                       1075
#define IDC_CHECK3                      1075
#define IDC_CHECK_LOG_FILE_SYNCHRONIZING 1075
#define IDC_CHECK4                      1076
#define IDC_CHECK_REMOVE_TEMP_FILE      1076
#define IDC_CHECK5                      1077
#define IDC_CHECK6                      1078
#define IDC_CHECK7                      1079
#define IDC_CHECK_SPEC_BREAK_HOLD       1079
#define IDC_CHECK8                      1080
#define IDC_CHECK_QUALITY_CONTROL_CHECK 1080
#define IDC_CHECK9                      1081
#define IDC_CHECK_BOM_OVER              1081
#define IDC_CHECK10                     1082
#define IDC_RADIO_SOURCE                1083
#define IDC_STATIC_OPTION               1084
#define IDC_RADIO_EDITED                1085
#define IDC_CHECK12                     1085
#define IDC_STATIC_SELECT_FROM          1086
#define IDC_CHECK13                     1086
#define IDC_CHECK_MAKE_PAINT_CODE       1086
#define IDC_CHECK11                     1087
#define IDC_CHECK_WELDING_DETAIL_CHECK  1087
#define IDC_BUTTON_PRINTER              1088
#define IDC_STATIC_SOURCE_PATH          1089
#define IDC_CHECK14                     1089
#define IDC_CHECK_MAKE_INS_BM           1089
#define IDC_STATIC_STATUS               1090
#define IDC_LIST_ISO_LIST               1091
#define IDC_STATIC_VIEW_LOG_FILE        1092
#define IDC_LIST_FILE_LIST              1093
#define IDC_CHECK15                     1093
#define IDC_CHECK16                     1094
#define IDC_CHECK_PIPE_SUPPORT          1094
#define IDC_BUTTON_PIPE_CUTTING_LENGTH  1095
#define IDC_LIST_SELECTED_LIST          1096
#define IDC_BUTTON_START                1097
#define IDC_CHECK_SCHEDULE_JOB          1098
#define IDC_BUTTON_VIEW_FILES           1099
#define IDC_BUTTON_ISSUE                1099
#define IDC_CHECK_SCHEDULE_JOB2         1099
#define IDC_CHECK_REV_AUTOMATION        1099
#define ID_CHECK_REV_AUTOMATION         1100
#define IDC_STATIC_ISO_DWG_FOLDER       1101
#define IDC_STATIC_1                    1102
#define IDC_STATIC_TITLE                1104
#define IDC_BUTTON_DBCONNECT            1105
#define IDC_BUTTON_GET                  1105
#define IDC_CHECK_SelectAll             1106
#define IDC_STATIC_QUALIFIED            1108
#define IDC_STATIC_OUTPUT               1109
#define IDC_EDIT_PRINTER                1112
#define IDC_CHECK_PLOTTING_AFTER_EDITING 1113
#define IDC_LIST_USER_DEFINED           1114
#define IDC_LIST_NEW_LINE_DATA          1116
#define IDC_STATIC_NEW                  1118
#define IDC_PROGRESS                    1119
#define IDC_STATIC_BACKUP_HISTORY       1120
#define IDC_STATIC_2                    1122
#define IDC_STATIC_3                    1123
#define IDC_STATIC_CONVERT              1124
#define IDC_STATIC_ROW_NUMBER           1125
#define IDC_BUTTON_GET_DATA_FROM_ISO_DWG 1126
#define IDC_CHECK_MAKE_PRT_FILE         1127
#define IDC_BUTTON_GET_DATA_FROM_ISO_IDF 1127
#define IDC_LIST_LINE_DATA              1128
#define IDC_CHECK_LOG_FILE_SYNCHORNIZING 1129
#define IDC_CHECK_SAVE_LOG_FILE         1130
#define IDC_CHECK_WELDING_DIA_CHECK     1131
#define IDC_CHECK_13_MATERIAL_CODE      1132
#define IDC_CHECK_MAKE_MERGE_FILE       1133
#define IDC_CHECK_GENERATE_INF_SUM_FILE 1133
#define IDC_CHECK_SELECT_FROM_ISSUE_DATE 1134
#define IDC_STATIC_TITLE2               1135
#define IDC_CHECK_SAVE_ERR_SUM          1135
#define IDC_CHECK_ERRREAD               1136
#define IDC_CHECK_DRWNO                 1137
#define IDC_CHECK_FGBERR                1138
#define IDC_CHECK_PIPECUTERR            1139
#define IDC_CHECK_NOTFOUNERR            1140
#define IDC_CHECK_FAILISOERR            1141
#define IDC_CHECK_PCDSYMERR             1142
#define IDC_CHECK_HOLDITEMERR           1143
#define IDC_CHECK_SPECBREAKERR          1144
#define IDC_CHECK_SYMCODEERR            1145
#define IDC_CHECK_SUPPORTBMERR          1146
#define IDC_CHECK_TEXTMODIFY            1147
#define IDC_LIST_SORT_NAME              1148
#define IDC_LIST_INSERTTOPDS            1150
#define IDC_BUTTON_SELECT_ALL_PDS       1151
#define IDC_BUTTON_UN_SELECT_ALL_PDS    1152
#define IDC_LIST_WRITE_PDS              1153
#define IDC_BUTTON_WRITE_PDS            1154
#define IDC_STATIC_WRITE_PDS            1155
#define IDC_CRYSEDITCTRLCTRL1           1162
#define IDC_CHECK_GENERATE_INF_FILE     1165
#define IDC_LIST_PRINT                  1168
#define IDC_STATIC_SELECTED_LINE        1172
#define IDC_STATIC_SELECTED_COUNT       1173
#define IDC_STATIC_SELECTED_INFO        1174
#define IDC_STATIC_QU_COUNT             1175
#define IDC_STATIC_SELECTED_COUNT2      1175
#define IDC_LIST_PLANT                  1176
#define IDC_STATIC_QUALIFIED_LINE       1176
#define IDC_LIST_AREA                   1177
#define IDC_CHECK_LINE_ID               1177
#define IDC_STATIC_QUALIFIED_COUNT      1177
#define IDC_LIST_UNIT                   1178
#define IDC_LIST_SECTION                1179
#define IDC_CHECK_CONFIRM_WITH_USTATION 1180
#define IDC_CHECK_MODIFY                1181
#define IDC_LIST_GET_PDS                1182
#define IDC_STATIC_APPLY_REV_DATE_TO_ALL 1182
#define IDC_STATIC_GET_PDS              1183
#define IDC_CHECK_SHOW_EXISTING_FILE    1184
#define IDC_STATIC_ABOUT                1186
#define IDC_STATIC_ISO_FOLDER           1187
#define IDC_STATIC_SOURCE_ISO_FOLDER    1187
#define IDC_BUTTON_GENERATE_ISO_PRODUCT 1519
#define IDC_BUTTON_GENERATE_DRAWING_REPORT 1520
#define IDC_BUTTON_PRINT_DRAWING        1521
#define IDC_BUTTON_UP                   1530
#define IDC_BUTTON_ISO_FOLDER           1531
#define IDC_STATIC_ISSUE_DATE           1532
#define IDC_STATIC_REVISION_STATE       1533
#define IDC_RADIO_CURRENT               1533
#define IDC_RADIO_ISSUED                1534
#define IDC_STATIC_WARNING_OPTION       1537
#define IDC_STATIC_SELECTION            1538
#define IDC_STATIC_REVISION_OPTION      1539
#define ID_CHECK_ISSUE_AUTOMATION       1540
#define IDC_LIST1                       1541
#define IDC_LIST_ISO_FILE               1541
#define IDC_CHECK2                      1542
#define IDC_CHECK_IPLOT                 1542
#define IDC_STATIC_MSG                  1543
#define IDC_STATIC_LICENSE_SERVER       1544
#define IDC_STATIC_LICENSE_ID           1545
#define IDC_STATIC_LICENSE_PASSWORD     1546
#define IDC_STATIC_PROJECT              1547
#define IDC_STATIC_USER                 1548
#define IDC_STATIC_PASSWORD             1549
#define IDC_STATIC_MODULE               1550
#define IDC_STATIC_OUTPUT_ISO_DRAWING_FOLDER 1551
#define IDC_BUTTON_GENERATE_BM          1553
#define IDB_LIST_HEADER                 20001
#define IDR_CRYEDIT_ACCEL               22901
#define ID_APP_CLOSE                    32771
#define ID_EDIT_REFRESH                 32771
#define ID_APP_PROPERTY                 32772
#define IDR_LINE_DATA_PRINT             32773
#define ID_LINE_DATA_PRINT              32774
#define ID_LINE_DATA_COPY               32775
#define ID_LINE_DATA_MODIFY             32776
#define ID_LINE_DATA_DELETE             32777
#define ID_LINE_DATA_UNDELETE           32778
#define ID_LINE_DATA_INSERT             32779
#define ID_LINE_DATA_QUALIFY            32780
#define ID_LINE_DATA_GET_DATA_FROM_ISO_DWG 32780
#define ID_OPTION_SETTING               32781
#define ID_ISO_EDIT_QUALIFY             32782
#define ID_DRAWING_REPORT_PRINT         32783
#define ID_LINE_LIST_COINCIDE_WITH      32784
#define ID_LINE_LIST_CONVERTER          32786
#define ID_LINE_DATA                    32787
#define ID_INSERT_TO_PDS_ATTR           32788
#define ID_GET_PDS_LINE_DATA            32789
#define ID_ISO_PRODUCT                  32790
#define ID_DRAWING_REPORT               32791
#define ID_BM_REPORT                    32792
#define ID_DRAWING_PLOTTING             32793
#define ID_SETTING_ADMIN                32794
#define ID_FILE_BACKUP                  32797
#define ID_FILE_ISSUE_MANAGER           32798
#define ID_LINE_LIST_CANCELLATION       32799
#define ID_BUTTON32800                  32800
#define ID_LINE_DATA_PROPERTIES         32801
#define ID_LINE_DATA_REPLACE            32802
#define ID_LINEDATA_DELETE              32803
#define ID_ISSUE_MANAGER_PROPERTIES     32804
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define IDS_TREE_ROOT_TITLE             61446
#define IDS_HEADER_FILENAME             61447
#define IDS_HEADER_FILESIZE             61448
#define IDS_HEADER_FILETYPE             61449
#define IDS_HEADER_LASTMODIFIED         61450
#define IDS_SIZE_KBS                    61451
#define IDS_SIZE_MBS                    61452
#define IDS_HEADER_REV_NO               61453
#define IDS_NO_RECORD                   61454
#define IDS_LINE_DATA_FORM_MSG1         61455
#define IDS_LINE_DATA_FORM_MSG2         61456
#define IDS_USER_APP_SETTING_TITLE      61457
#define IDS_COMPARE_DATA_MSG1           61458
#define IDS_COMPARE_DATA_MSG2           61459
#define IDS_COMPARE_DATA_MSG3           61460
#define IDS_CONVERT_OK                  61461
#define IDS_DUPLICATED_PRIMARY_KEY      61462
#define IDS_LAST_DATE                   61463
#define IDS_BORDER_SETTING_ERROR        61464
#define IDS_ISO_EDIT_SETTING_ERROR      61465
#define IDS_SELECT_ISO_FILE             61466
#define IDS_UPDATE_DATABASE_OK          61467
#define IDS_UPDATE_DATABASE_ERROR       61468
#define IDS_LOG_FILE_NAME_FORMAT        61469
#define IDS_PAINT_FILE_NAME_FORMAT      61470
#define IDS_INS_FILE_NAME_FORMAT        61471
#define IDS_WELD_DETAIL_FILE_NAME_FORMAT 61472
#define IDS_WELD_DIA_CHECK              61473
#define IDS_CONNECT_ORACLE_ERROR        61474
#define IDS_INF_SUM_FILE_NAME_FORMAT    61475
#define IDS_TOO_MANY_RECORDS            61476
#define IDS_DESIGN_DDL_FIELD_ERROR      61477
#define IDS_NOT_ADMITTED_CHAR           61478
#define IDS_NO_FILE                     61479
#define IDS_NO_MSTATION_PATH            61480
#define IDS_FAIL_TO_OPEN_QUERY          61481
#define IDS_NEED_ISSUE_DATE_TO_QUERY    61482
#define IDS_ORACLE_CONNECTION_ERROR     61483
#define IDS_DUPLICATED_ISOMAN_KEY       61484
#define IDS_INF_PIPING_FILE_NAME_FORMAT 61485
#define IDS_INF_OTHERS_FILE_NAME_FORMAT 61486
#define IDS_PIPE_SUPPORT_CHECK          61487
#define IDS_DUPLICATED_LINE_DATA_MODULE_KEY 61488

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1554
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
