/* soapH.h
   Generated by gSOAP 2.8.22 from LicWebService.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data), 0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data), 0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedByte(soap, data), 0) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedInt(soap, data), 0) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_bool(soap, data), 0) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__ns1__ResetResponse
#define SOAP_TYPE__ns1__ResetResponse (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ResetResponse(struct soap*, const char*, int, const _ns1__ResetResponse *, const char*);
SOAP_FMAC3 _ns1__ResetResponse * SOAP_FMAC4 soap_in__ns1__ResetResponse(struct soap*, const char*, _ns1__ResetResponse *, const char*);

#ifndef soap_write__ns1__ResetResponse
#define soap_write__ns1__ResetResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:ResetResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__ResetResponse * SOAP_FMAC4 soap_get__ns1__ResetResponse(struct soap*, _ns1__ResetResponse *, const char*, const char*);

#ifndef soap_read__ns1__ResetResponse
#define soap_read__ns1__ResetResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__ResetResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__ResetResponse * SOAP_FMAC2 soap_instantiate__ns1__ResetResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__ResetResponse * soap_new__ns1__ResetResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__ResetResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__ResetResponse * soap_new_req__ns1__ResetResponse(struct soap *soap, ns1__LMSStuctType *ResetResult) { _ns1__ResetResponse *_p = soap_instantiate__ns1__ResetResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__ResetResponse::ResetResult = ResetResult; } return _p; }

inline _ns1__ResetResponse * soap_new_set__ns1__ResetResponse(struct soap *soap, ns1__LMSStuctType *ResetResult) { _ns1__ResetResponse *_p = soap_instantiate__ns1__ResetResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__ResetResponse::ResetResult = ResetResult; } return _p; }

inline void soap_delete__ns1__ResetResponse(struct soap *soap, _ns1__ResetResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ResetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Reset
#define SOAP_TYPE__ns1__Reset (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Reset(struct soap*, const char*, int, const _ns1__Reset *, const char*);
SOAP_FMAC3 _ns1__Reset * SOAP_FMAC4 soap_in__ns1__Reset(struct soap*, const char*, _ns1__Reset *, const char*);

#ifndef soap_write__ns1__Reset
#define soap_write__ns1__Reset(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Reset", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Reset * SOAP_FMAC4 soap_get__ns1__Reset(struct soap*, _ns1__Reset *, const char*, const char*);

#ifndef soap_read__ns1__Reset
#define soap_read__ns1__Reset(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Reset(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__Reset * SOAP_FMAC2 soap_instantiate__ns1__Reset(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__Reset * soap_new__ns1__Reset(struct soap *soap, int n = -1) { return soap_instantiate__ns1__Reset(soap, n, NULL, NULL, NULL); }

inline _ns1__Reset * soap_new_req__ns1__Reset(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Reset *_p = soap_instantiate__ns1__Reset(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Reset::oLMS = oLMS; } return _p; }

inline _ns1__Reset * soap_new_set__ns1__Reset(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Reset *_p = soap_instantiate__ns1__Reset(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Reset::oLMS = oLMS; } return _p; }

inline void soap_delete__ns1__Reset(struct soap *soap, _ns1__Reset *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Reset(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__LogoutResponse
#define SOAP_TYPE__ns1__LogoutResponse (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__LogoutResponse(struct soap*, const char*, int, const _ns1__LogoutResponse *, const char*);
SOAP_FMAC3 _ns1__LogoutResponse * SOAP_FMAC4 soap_in__ns1__LogoutResponse(struct soap*, const char*, _ns1__LogoutResponse *, const char*);

#ifndef soap_write__ns1__LogoutResponse
#define soap_write__ns1__LogoutResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:LogoutResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LogoutResponse * SOAP_FMAC4 soap_get__ns1__LogoutResponse(struct soap*, _ns1__LogoutResponse *, const char*, const char*);

#ifndef soap_read__ns1__LogoutResponse
#define soap_read__ns1__LogoutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__LogoutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__LogoutResponse * SOAP_FMAC2 soap_instantiate__ns1__LogoutResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__LogoutResponse * soap_new__ns1__LogoutResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__LogoutResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__LogoutResponse * soap_new_req__ns1__LogoutResponse(struct soap *soap, ns1__LMSStuctType *LogoutResult) { _ns1__LogoutResponse *_p = soap_instantiate__ns1__LogoutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__LogoutResponse::LogoutResult = LogoutResult; } return _p; }

inline _ns1__LogoutResponse * soap_new_set__ns1__LogoutResponse(struct soap *soap, ns1__LMSStuctType *LogoutResult) { _ns1__LogoutResponse *_p = soap_instantiate__ns1__LogoutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__LogoutResponse::LogoutResult = LogoutResult; } return _p; }

inline void soap_delete__ns1__LogoutResponse(struct soap *soap, _ns1__LogoutResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__LogoutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Logout
#define SOAP_TYPE__ns1__Logout (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Logout(struct soap*, const char*, int, const _ns1__Logout *, const char*);
SOAP_FMAC3 _ns1__Logout * SOAP_FMAC4 soap_in__ns1__Logout(struct soap*, const char*, _ns1__Logout *, const char*);

#ifndef soap_write__ns1__Logout
#define soap_write__ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Logout * SOAP_FMAC4 soap_get__ns1__Logout(struct soap*, _ns1__Logout *, const char*, const char*);

#ifndef soap_read__ns1__Logout
#define soap_read__ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__Logout * SOAP_FMAC2 soap_instantiate__ns1__Logout(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__Logout * soap_new__ns1__Logout(struct soap *soap, int n = -1) { return soap_instantiate__ns1__Logout(soap, n, NULL, NULL, NULL); }

inline _ns1__Logout * soap_new_req__ns1__Logout(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Logout *_p = soap_instantiate__ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Logout::oLMS = oLMS; } return _p; }

inline _ns1__Logout * soap_new_set__ns1__Logout(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Logout *_p = soap_instantiate__ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Logout::oLMS = oLMS; } return _p; }

inline void soap_delete__ns1__Logout(struct soap *soap, _ns1__Logout *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Logout(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__IsValidTokenResponse
#define SOAP_TYPE__ns1__IsValidTokenResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__IsValidTokenResponse(struct soap*, const char*, int, const _ns1__IsValidTokenResponse *, const char*);
SOAP_FMAC3 _ns1__IsValidTokenResponse * SOAP_FMAC4 soap_in__ns1__IsValidTokenResponse(struct soap*, const char*, _ns1__IsValidTokenResponse *, const char*);

#ifndef soap_write__ns1__IsValidTokenResponse
#define soap_write__ns1__IsValidTokenResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:IsValidTokenResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__IsValidTokenResponse * SOAP_FMAC4 soap_get__ns1__IsValidTokenResponse(struct soap*, _ns1__IsValidTokenResponse *, const char*, const char*);

#ifndef soap_read__ns1__IsValidTokenResponse
#define soap_read__ns1__IsValidTokenResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__IsValidTokenResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__IsValidTokenResponse * SOAP_FMAC2 soap_instantiate__ns1__IsValidTokenResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__IsValidTokenResponse * soap_new__ns1__IsValidTokenResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__IsValidTokenResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__IsValidTokenResponse * soap_new_req__ns1__IsValidTokenResponse(struct soap *soap, bool IsValidTokenResult) { _ns1__IsValidTokenResponse *_p = soap_instantiate__ns1__IsValidTokenResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__IsValidTokenResponse::IsValidTokenResult = IsValidTokenResult; } return _p; }

inline _ns1__IsValidTokenResponse * soap_new_set__ns1__IsValidTokenResponse(struct soap *soap, bool IsValidTokenResult) { _ns1__IsValidTokenResponse *_p = soap_instantiate__ns1__IsValidTokenResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__IsValidTokenResponse::IsValidTokenResult = IsValidTokenResult; } return _p; }

inline void soap_delete__ns1__IsValidTokenResponse(struct soap *soap, _ns1__IsValidTokenResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__IsValidTokenResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__IsValidToken
#define SOAP_TYPE__ns1__IsValidToken (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__IsValidToken(struct soap*, const char*, int, const _ns1__IsValidToken *, const char*);
SOAP_FMAC3 _ns1__IsValidToken * SOAP_FMAC4 soap_in__ns1__IsValidToken(struct soap*, const char*, _ns1__IsValidToken *, const char*);

#ifndef soap_write__ns1__IsValidToken
#define soap_write__ns1__IsValidToken(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:IsValidToken", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__IsValidToken * SOAP_FMAC4 soap_get__ns1__IsValidToken(struct soap*, _ns1__IsValidToken *, const char*, const char*);

#ifndef soap_read__ns1__IsValidToken
#define soap_read__ns1__IsValidToken(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__IsValidToken(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__IsValidToken * SOAP_FMAC2 soap_instantiate__ns1__IsValidToken(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__IsValidToken * soap_new__ns1__IsValidToken(struct soap *soap, int n = -1) { return soap_instantiate__ns1__IsValidToken(soap, n, NULL, NULL, NULL); }

inline _ns1__IsValidToken * soap_new_req__ns1__IsValidToken(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__IsValidToken *_p = soap_instantiate__ns1__IsValidToken(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__IsValidToken::oLMS = oLMS; } return _p; }

inline _ns1__IsValidToken * soap_new_set__ns1__IsValidToken(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__IsValidToken *_p = soap_instantiate__ns1__IsValidToken(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__IsValidToken::oLMS = oLMS; } return _p; }

inline void soap_delete__ns1__IsValidToken(struct soap *soap, _ns1__IsValidToken *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__IsValidToken(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__LoginResponse
#define SOAP_TYPE__ns1__LoginResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__LoginResponse(struct soap*, const char*, int, const _ns1__LoginResponse *, const char*);
SOAP_FMAC3 _ns1__LoginResponse * SOAP_FMAC4 soap_in__ns1__LoginResponse(struct soap*, const char*, _ns1__LoginResponse *, const char*);

#ifndef soap_write__ns1__LoginResponse
#define soap_write__ns1__LoginResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:LoginResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LoginResponse * SOAP_FMAC4 soap_get__ns1__LoginResponse(struct soap*, _ns1__LoginResponse *, const char*, const char*);

#ifndef soap_read__ns1__LoginResponse
#define soap_read__ns1__LoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__LoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__LoginResponse * SOAP_FMAC2 soap_instantiate__ns1__LoginResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__LoginResponse * soap_new__ns1__LoginResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__LoginResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__LoginResponse * soap_new_req__ns1__LoginResponse(struct soap *soap, ns1__LMSStuctType *LoginResult) { _ns1__LoginResponse *_p = soap_instantiate__ns1__LoginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__LoginResponse::LoginResult = LoginResult; } return _p; }

inline _ns1__LoginResponse * soap_new_set__ns1__LoginResponse(struct soap *soap, ns1__LMSStuctType *LoginResult) { _ns1__LoginResponse *_p = soap_instantiate__ns1__LoginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__LoginResponse::LoginResult = LoginResult; } return _p; }

inline void soap_delete__ns1__LoginResponse(struct soap *soap, _ns1__LoginResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__LoginResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Login
#define SOAP_TYPE__ns1__Login (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Login(struct soap*, const char*, int, const _ns1__Login *, const char*);
SOAP_FMAC3 _ns1__Login * SOAP_FMAC4 soap_in__ns1__Login(struct soap*, const char*, _ns1__Login *, const char*);

#ifndef soap_write__ns1__Login
#define soap_write__ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Login * SOAP_FMAC4 soap_get__ns1__Login(struct soap*, _ns1__Login *, const char*, const char*);

#ifndef soap_read__ns1__Login
#define soap_read__ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__Login * SOAP_FMAC2 soap_instantiate__ns1__Login(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__Login * soap_new__ns1__Login(struct soap *soap, int n = -1) { return soap_instantiate__ns1__Login(soap, n, NULL, NULL, NULL); }

inline _ns1__Login * soap_new_req__ns1__Login(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Login *_p = soap_instantiate__ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Login::oLMS = oLMS; } return _p; }

inline _ns1__Login * soap_new_set__ns1__Login(struct soap *soap, ns1__LMSStuctType *oLMS) { _ns1__Login *_p = soap_instantiate__ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Login::oLMS = oLMS; } return _p; }

inline void soap_delete__ns1__Login(struct soap *soap, _ns1__Login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__LMSStuctType
#define SOAP_TYPE_ns1__LMSStuctType (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__LMSStuctType(struct soap*, const char*, int, const ns1__LMSStuctType *, const char*);
SOAP_FMAC3 ns1__LMSStuctType * SOAP_FMAC4 soap_in_ns1__LMSStuctType(struct soap*, const char*, ns1__LMSStuctType *, const char*);

#ifndef soap_write_ns1__LMSStuctType
#define soap_write_ns1__LMSStuctType(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:LMSStuctType", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__LMSStuctType * SOAP_FMAC4 soap_get_ns1__LMSStuctType(struct soap*, ns1__LMSStuctType *, const char*, const char*);

#ifndef soap_read_ns1__LMSStuctType
#define soap_read_ns1__LMSStuctType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__LMSStuctType(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns1__LMSStuctType * SOAP_FMAC2 soap_instantiate_ns1__LMSStuctType(struct soap*, int, const char*, const char*, size_t*);

inline ns1__LMSStuctType * soap_new_ns1__LMSStuctType(struct soap *soap, int n = -1) { return soap_instantiate_ns1__LMSStuctType(soap, n, NULL, NULL, NULL); }

inline ns1__LMSStuctType * soap_new_req_ns1__LMSStuctType(struct soap *soap, int size) { ns1__LMSStuctType *_p = soap_instantiate_ns1__LMSStuctType(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__LMSStuctType::size = size; } return _p; }

inline ns1__LMSStuctType * soap_new_set_ns1__LMSStuctType(struct soap *soap, int size, xsd__base64Binary *buf) { ns1__LMSStuctType *_p = soap_instantiate_ns1__LMSStuctType(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__LMSStuctType::size = size; _p->ns1__LMSStuctType::buf = buf; } return _p; }

inline void soap_delete_ns1__LMSStuctType(struct soap *soap, ns1__LMSStuctType *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__LMSStuctType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (8)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);

#ifndef soap_write_xsd__base64Binary
#define soap_write_xsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);

#ifndef soap_read_xsd__base64Binary
#define soap_read_xsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 xsd__base64Binary * SOAP_FMAC2 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);

inline xsd__base64Binary * soap_new_xsd__base64Binary(struct soap *soap, int n = -1) { return soap_instantiate_xsd__base64Binary(soap, n, NULL, NULL, NULL); }

inline xsd__base64Binary * soap_new_req_xsd__base64Binary(struct soap *soap) { xsd__base64Binary *_p = soap_instantiate_xsd__base64Binary(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline xsd__base64Binary * soap_new_set_xsd__base64Binary(struct soap *soap, unsigned char *__ptr, int __size, char *id, char *type, char *options) { xsd__base64Binary *_p = soap_instantiate_xsd__base64Binary(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->xsd__base64Binary::__ptr = __ptr; _p->xsd__base64Binary::__size = __size; _p->xsd__base64Binary::id = id; _p->xsd__base64Binary::type = type; _p->xsd__base64Binary::options = options; } return _p; }

inline void soap_delete_xsd__base64Binary(struct soap *soap, xsd__base64Binary *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__Reset_
#define SOAP_TYPE___ns1__Reset_ (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Reset_(struct soap*, struct __ns1__Reset_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Reset_(struct soap*, const struct __ns1__Reset_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Reset_(struct soap*, const char*, int, const struct __ns1__Reset_ *, const char*);
SOAP_FMAC3 struct __ns1__Reset_ * SOAP_FMAC4 soap_in___ns1__Reset_(struct soap*, const char*, struct __ns1__Reset_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Reset_(struct soap*, const struct __ns1__Reset_ *, const char*, const char*);

#ifndef soap_write___ns1__Reset_
#define soap_write___ns1__Reset_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Reset_(soap, data), 0) || soap_put___ns1__Reset_(soap, data, "-ns1:Reset", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Reset_ * SOAP_FMAC4 soap_get___ns1__Reset_(struct soap*, struct __ns1__Reset_ *, const char*, const char*);

#ifndef soap_read___ns1__Reset_
#define soap_read___ns1__Reset_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Reset_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Reset_ * SOAP_FMAC2 soap_instantiate___ns1__Reset_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Reset_ * soap_new___ns1__Reset_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Reset_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Reset_ * soap_new_req___ns1__Reset_(struct soap *soap) { struct __ns1__Reset_ *_p = soap_instantiate___ns1__Reset_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Reset_(soap, _p); } return _p; }

inline struct __ns1__Reset_ * soap_new_set___ns1__Reset_(struct soap *soap, _ns1__Reset *ns1__Reset) { struct __ns1__Reset_ *_p = soap_instantiate___ns1__Reset_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Reset_(soap, _p); _p->ns1__Reset = ns1__Reset; } return _p; }

inline void soap_delete___ns1__Reset_(struct soap *soap, struct __ns1__Reset_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Reset_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Logout_
#define SOAP_TYPE___ns1__Logout_ (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Logout_(struct soap*, struct __ns1__Logout_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Logout_(struct soap*, const struct __ns1__Logout_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Logout_(struct soap*, const char*, int, const struct __ns1__Logout_ *, const char*);
SOAP_FMAC3 struct __ns1__Logout_ * SOAP_FMAC4 soap_in___ns1__Logout_(struct soap*, const char*, struct __ns1__Logout_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Logout_(struct soap*, const struct __ns1__Logout_ *, const char*, const char*);

#ifndef soap_write___ns1__Logout_
#define soap_write___ns1__Logout_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Logout_(soap, data), 0) || soap_put___ns1__Logout_(soap, data, "-ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Logout_ * SOAP_FMAC4 soap_get___ns1__Logout_(struct soap*, struct __ns1__Logout_ *, const char*, const char*);

#ifndef soap_read___ns1__Logout_
#define soap_read___ns1__Logout_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Logout_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Logout_ * SOAP_FMAC2 soap_instantiate___ns1__Logout_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Logout_ * soap_new___ns1__Logout_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Logout_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Logout_ * soap_new_req___ns1__Logout_(struct soap *soap) { struct __ns1__Logout_ *_p = soap_instantiate___ns1__Logout_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout_(soap, _p); } return _p; }

inline struct __ns1__Logout_ * soap_new_set___ns1__Logout_(struct soap *soap, _ns1__Logout *ns1__Logout) { struct __ns1__Logout_ *_p = soap_instantiate___ns1__Logout_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout_(soap, _p); _p->ns1__Logout = ns1__Logout; } return _p; }

inline void soap_delete___ns1__Logout_(struct soap *soap, struct __ns1__Logout_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Logout_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__IsValidToken_
#define SOAP_TYPE___ns1__IsValidToken_ (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__IsValidToken_(struct soap*, struct __ns1__IsValidToken_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__IsValidToken_(struct soap*, const struct __ns1__IsValidToken_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__IsValidToken_(struct soap*, const char*, int, const struct __ns1__IsValidToken_ *, const char*);
SOAP_FMAC3 struct __ns1__IsValidToken_ * SOAP_FMAC4 soap_in___ns1__IsValidToken_(struct soap*, const char*, struct __ns1__IsValidToken_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__IsValidToken_(struct soap*, const struct __ns1__IsValidToken_ *, const char*, const char*);

#ifndef soap_write___ns1__IsValidToken_
#define soap_write___ns1__IsValidToken_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__IsValidToken_(soap, data), 0) || soap_put___ns1__IsValidToken_(soap, data, "-ns1:IsValidToken", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__IsValidToken_ * SOAP_FMAC4 soap_get___ns1__IsValidToken_(struct soap*, struct __ns1__IsValidToken_ *, const char*, const char*);

#ifndef soap_read___ns1__IsValidToken_
#define soap_read___ns1__IsValidToken_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__IsValidToken_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__IsValidToken_ * SOAP_FMAC2 soap_instantiate___ns1__IsValidToken_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__IsValidToken_ * soap_new___ns1__IsValidToken_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__IsValidToken_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__IsValidToken_ * soap_new_req___ns1__IsValidToken_(struct soap *soap) { struct __ns1__IsValidToken_ *_p = soap_instantiate___ns1__IsValidToken_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__IsValidToken_(soap, _p); } return _p; }

inline struct __ns1__IsValidToken_ * soap_new_set___ns1__IsValidToken_(struct soap *soap, _ns1__IsValidToken *ns1__IsValidToken) { struct __ns1__IsValidToken_ *_p = soap_instantiate___ns1__IsValidToken_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__IsValidToken_(soap, _p); _p->ns1__IsValidToken = ns1__IsValidToken; } return _p; }

inline void soap_delete___ns1__IsValidToken_(struct soap *soap, struct __ns1__IsValidToken_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__IsValidToken_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Login_
#define SOAP_TYPE___ns1__Login_ (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Login_(struct soap*, struct __ns1__Login_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Login_(struct soap*, const struct __ns1__Login_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Login_(struct soap*, const char*, int, const struct __ns1__Login_ *, const char*);
SOAP_FMAC3 struct __ns1__Login_ * SOAP_FMAC4 soap_in___ns1__Login_(struct soap*, const char*, struct __ns1__Login_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Login_(struct soap*, const struct __ns1__Login_ *, const char*, const char*);

#ifndef soap_write___ns1__Login_
#define soap_write___ns1__Login_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Login_(soap, data), 0) || soap_put___ns1__Login_(soap, data, "-ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Login_ * SOAP_FMAC4 soap_get___ns1__Login_(struct soap*, struct __ns1__Login_ *, const char*, const char*);

#ifndef soap_read___ns1__Login_
#define soap_read___ns1__Login_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Login_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Login_ * SOAP_FMAC2 soap_instantiate___ns1__Login_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Login_ * soap_new___ns1__Login_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Login_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Login_ * soap_new_req___ns1__Login_(struct soap *soap) { struct __ns1__Login_ *_p = soap_instantiate___ns1__Login_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login_(soap, _p); } return _p; }

inline struct __ns1__Login_ * soap_new_set___ns1__Login_(struct soap *soap, _ns1__Login *ns1__Login) { struct __ns1__Login_ *_p = soap_instantiate___ns1__Login_(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login_(soap, _p); _p->ns1__Login = ns1__Login; } return _p; }

inline void soap_delete___ns1__Login_(struct soap *soap, struct __ns1__Login_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Login_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Reset
#define SOAP_TYPE___ns1__Reset (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Reset(struct soap*, struct __ns1__Reset *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Reset(struct soap*, const struct __ns1__Reset *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Reset(struct soap*, const char*, int, const struct __ns1__Reset *, const char*);
SOAP_FMAC3 struct __ns1__Reset * SOAP_FMAC4 soap_in___ns1__Reset(struct soap*, const char*, struct __ns1__Reset *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Reset(struct soap*, const struct __ns1__Reset *, const char*, const char*);

#ifndef soap_write___ns1__Reset
#define soap_write___ns1__Reset(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Reset(soap, data), 0) || soap_put___ns1__Reset(soap, data, "-ns1:Reset", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Reset * SOAP_FMAC4 soap_get___ns1__Reset(struct soap*, struct __ns1__Reset *, const char*, const char*);

#ifndef soap_read___ns1__Reset
#define soap_read___ns1__Reset(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Reset(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Reset * SOAP_FMAC2 soap_instantiate___ns1__Reset(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Reset * soap_new___ns1__Reset(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Reset(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Reset * soap_new_req___ns1__Reset(struct soap *soap) { struct __ns1__Reset *_p = soap_instantiate___ns1__Reset(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Reset(soap, _p); } return _p; }

inline struct __ns1__Reset * soap_new_set___ns1__Reset(struct soap *soap, _ns1__Reset *ns1__Reset) { struct __ns1__Reset *_p = soap_instantiate___ns1__Reset(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Reset(soap, _p); _p->ns1__Reset = ns1__Reset; } return _p; }

inline void soap_delete___ns1__Reset(struct soap *soap, struct __ns1__Reset *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Reset(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Logout
#define SOAP_TYPE___ns1__Logout (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Logout(struct soap*, struct __ns1__Logout *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Logout(struct soap*, const struct __ns1__Logout *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Logout(struct soap*, const char*, int, const struct __ns1__Logout *, const char*);
SOAP_FMAC3 struct __ns1__Logout * SOAP_FMAC4 soap_in___ns1__Logout(struct soap*, const char*, struct __ns1__Logout *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Logout(struct soap*, const struct __ns1__Logout *, const char*, const char*);

#ifndef soap_write___ns1__Logout
#define soap_write___ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Logout(soap, data), 0) || soap_put___ns1__Logout(soap, data, "-ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Logout * SOAP_FMAC4 soap_get___ns1__Logout(struct soap*, struct __ns1__Logout *, const char*, const char*);

#ifndef soap_read___ns1__Logout
#define soap_read___ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Logout * SOAP_FMAC2 soap_instantiate___ns1__Logout(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Logout * soap_new___ns1__Logout(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Logout(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Logout * soap_new_req___ns1__Logout(struct soap *soap) { struct __ns1__Logout *_p = soap_instantiate___ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout(soap, _p); } return _p; }

inline struct __ns1__Logout * soap_new_set___ns1__Logout(struct soap *soap, _ns1__Logout *ns1__Logout) { struct __ns1__Logout *_p = soap_instantiate___ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout(soap, _p); _p->ns1__Logout = ns1__Logout; } return _p; }

inline void soap_delete___ns1__Logout(struct soap *soap, struct __ns1__Logout *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Logout(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__IsValidToken
#define SOAP_TYPE___ns1__IsValidToken (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__IsValidToken(struct soap*, struct __ns1__IsValidToken *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__IsValidToken(struct soap*, const struct __ns1__IsValidToken *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__IsValidToken(struct soap*, const char*, int, const struct __ns1__IsValidToken *, const char*);
SOAP_FMAC3 struct __ns1__IsValidToken * SOAP_FMAC4 soap_in___ns1__IsValidToken(struct soap*, const char*, struct __ns1__IsValidToken *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__IsValidToken(struct soap*, const struct __ns1__IsValidToken *, const char*, const char*);

#ifndef soap_write___ns1__IsValidToken
#define soap_write___ns1__IsValidToken(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__IsValidToken(soap, data), 0) || soap_put___ns1__IsValidToken(soap, data, "-ns1:IsValidToken", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__IsValidToken * SOAP_FMAC4 soap_get___ns1__IsValidToken(struct soap*, struct __ns1__IsValidToken *, const char*, const char*);

#ifndef soap_read___ns1__IsValidToken
#define soap_read___ns1__IsValidToken(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__IsValidToken(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__IsValidToken * SOAP_FMAC2 soap_instantiate___ns1__IsValidToken(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__IsValidToken * soap_new___ns1__IsValidToken(struct soap *soap, int n = -1) { return soap_instantiate___ns1__IsValidToken(soap, n, NULL, NULL, NULL); }

inline struct __ns1__IsValidToken * soap_new_req___ns1__IsValidToken(struct soap *soap) { struct __ns1__IsValidToken *_p = soap_instantiate___ns1__IsValidToken(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__IsValidToken(soap, _p); } return _p; }

inline struct __ns1__IsValidToken * soap_new_set___ns1__IsValidToken(struct soap *soap, _ns1__IsValidToken *ns1__IsValidToken) { struct __ns1__IsValidToken *_p = soap_instantiate___ns1__IsValidToken(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__IsValidToken(soap, _p); _p->ns1__IsValidToken = ns1__IsValidToken; } return _p; }

inline void soap_delete___ns1__IsValidToken(struct soap *soap, struct __ns1__IsValidToken *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__IsValidToken(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Login
#define SOAP_TYPE___ns1__Login (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Login(struct soap*, struct __ns1__Login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Login(struct soap*, const struct __ns1__Login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Login(struct soap*, const char*, int, const struct __ns1__Login *, const char*);
SOAP_FMAC3 struct __ns1__Login * SOAP_FMAC4 soap_in___ns1__Login(struct soap*, const char*, struct __ns1__Login *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Login(struct soap*, const struct __ns1__Login *, const char*, const char*);

#ifndef soap_write___ns1__Login
#define soap_write___ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Login(soap, data), 0) || soap_put___ns1__Login(soap, data, "-ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Login * SOAP_FMAC4 soap_get___ns1__Login(struct soap*, struct __ns1__Login *, const char*, const char*);

#ifndef soap_read___ns1__Login
#define soap_read___ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Login * SOAP_FMAC2 soap_instantiate___ns1__Login(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Login * soap_new___ns1__Login(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Login(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Login * soap_new_req___ns1__Login(struct soap *soap) { struct __ns1__Login *_p = soap_instantiate___ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login(soap, _p); } return _p; }

inline struct __ns1__Login * soap_new_set___ns1__Login(struct soap *soap, _ns1__Login *ns1__Login) { struct __ns1__Login *_p = soap_instantiate___ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login(soap, _p); _p->ns1__Login = ns1__Login; } return _p; }

inline void soap_delete___ns1__Login(struct soap *soap, struct __ns1__Login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__Reset
#define SOAP_TYPE_PointerTo_ns1__Reset (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Reset(struct soap*, _ns1__Reset *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Reset(struct soap*, const char *, int, _ns1__Reset *const*, const char *);
SOAP_FMAC3 _ns1__Reset ** SOAP_FMAC4 soap_in_PointerTo_ns1__Reset(struct soap*, const char*, _ns1__Reset **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Reset(struct soap*, _ns1__Reset *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__Reset
#define soap_write_PointerTo_ns1__Reset(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Reset(soap, data), 0) || soap_put_PointerTo_ns1__Reset(soap, data, "ns1:Reset", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Reset ** SOAP_FMAC4 soap_get_PointerTo_ns1__Reset(struct soap*, _ns1__Reset **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Reset
#define soap_read_PointerTo_ns1__Reset(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Reset(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__Logout
#define SOAP_TYPE_PointerTo_ns1__Logout (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Logout(struct soap*, _ns1__Logout *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Logout(struct soap*, const char *, int, _ns1__Logout *const*, const char *);
SOAP_FMAC3 _ns1__Logout ** SOAP_FMAC4 soap_in_PointerTo_ns1__Logout(struct soap*, const char*, _ns1__Logout **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Logout(struct soap*, _ns1__Logout *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__Logout
#define soap_write_PointerTo_ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Logout(soap, data), 0) || soap_put_PointerTo_ns1__Logout(soap, data, "ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Logout ** SOAP_FMAC4 soap_get_PointerTo_ns1__Logout(struct soap*, _ns1__Logout **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Logout
#define soap_read_PointerTo_ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__IsValidToken
#define SOAP_TYPE_PointerTo_ns1__IsValidToken (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__IsValidToken(struct soap*, _ns1__IsValidToken *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__IsValidToken(struct soap*, const char *, int, _ns1__IsValidToken *const*, const char *);
SOAP_FMAC3 _ns1__IsValidToken ** SOAP_FMAC4 soap_in_PointerTo_ns1__IsValidToken(struct soap*, const char*, _ns1__IsValidToken **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__IsValidToken(struct soap*, _ns1__IsValidToken *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__IsValidToken
#define soap_write_PointerTo_ns1__IsValidToken(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__IsValidToken(soap, data), 0) || soap_put_PointerTo_ns1__IsValidToken(soap, data, "ns1:IsValidToken", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__IsValidToken ** SOAP_FMAC4 soap_get_PointerTo_ns1__IsValidToken(struct soap*, _ns1__IsValidToken **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__IsValidToken
#define soap_read_PointerTo_ns1__IsValidToken(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__IsValidToken(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__Login
#define SOAP_TYPE_PointerTo_ns1__Login (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Login(struct soap*, _ns1__Login *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Login(struct soap*, const char *, int, _ns1__Login *const*, const char *);
SOAP_FMAC3 _ns1__Login ** SOAP_FMAC4 soap_in_PointerTo_ns1__Login(struct soap*, const char*, _ns1__Login **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Login(struct soap*, _ns1__Login *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__Login
#define soap_write_PointerTo_ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Login(soap, data), 0) || soap_put_PointerTo_ns1__Login(soap, data, "ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Login ** SOAP_FMAC4 soap_get_PointerTo_ns1__Login(struct soap*, _ns1__Login **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Login
#define soap_read_PointerTo_ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__LMSStuctType
#define SOAP_TYPE_PointerTons1__LMSStuctType (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__LMSStuctType(struct soap*, ns1__LMSStuctType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__LMSStuctType(struct soap*, const char *, int, ns1__LMSStuctType *const*, const char *);
SOAP_FMAC3 ns1__LMSStuctType ** SOAP_FMAC4 soap_in_PointerTons1__LMSStuctType(struct soap*, const char*, ns1__LMSStuctType **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__LMSStuctType(struct soap*, ns1__LMSStuctType *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__LMSStuctType
#define soap_write_PointerTons1__LMSStuctType(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons1__LMSStuctType(soap, data), 0) || soap_put_PointerTons1__LMSStuctType(soap, data, "ns1:LMSStuctType", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns1__LMSStuctType ** SOAP_FMAC4 soap_get_PointerTons1__LMSStuctType(struct soap*, ns1__LMSStuctType **, const char*, const char*);

#ifndef soap_read_PointerTons1__LMSStuctType
#define soap_read_PointerTons1__LMSStuctType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__LMSStuctType(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, xsd__base64Binary *const*, const char *);
SOAP_FMAC3 xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, xsd__base64Binary **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary *const*, const char*, const char*);

#ifndef soap_write_PointerToxsd__base64Binary
#define soap_write_PointerToxsd__base64Binary(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToxsd__base64Binary(soap, data), 0) || soap_put_PointerToxsd__base64Binary(soap, data, "xsd:base64Binary", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, xsd__base64Binary **, const char*, const char*);

#ifndef soap_read_PointerToxsd__base64Binary
#define soap_read_PointerToxsd__base64Binary(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToxsd__base64Binary(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTounsignedByte(soap, data), 0) || soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of soapH.h */
